//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int BillID { get; set; }
        public int Biller_User_ID { get; set; }
        public int AppointmentID { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime BillDate { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual User User { get; set; }
    }
}
