//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy_Billing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pharmacy_Billing()
        {
            this.Medicine_Billing = new HashSet<Medicine_Billing>();
        }
    
        public int Pharmacy_Billing_ID { get; set; }
        public int Pharmacists_User_ID { get; set; }
        public Nullable<int> Patient_User_ID { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime Date { get; set; }
        public double Subtotal { get; set; }
        public double Discount { get; set; }
        public double Total { get; set; }
        public string Invoice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicine_Billing> Medicine_Billing { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
