//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescribed_Tests
    {
        public int Prescribed_Tests_ID { get; set; }
        public int PrescriptionID { get; set; }
        public int TestID { get; set; }
    
        public virtual MedicalTest MedicalTest { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
