//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescribed_Medicines
    {
        public int Prescribed_Medicines_ID { get; set; }
        public int PrescriptionID { get; set; }
        public int MedicineID { get; set; }
        public string Dosage { get; set; }
        public string Instructions { get; set; }
        public string Feed_Days { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
